// Generated by scripts/build-blog.py from content/blog/.
window.GOODBOY_POSTS = [
  {
    "slug": "sensor-fusion-without-false-certainty",
    "title": "Sensor fusion should preserve doubt",
    "excerpt": "Combining physical signals without confusing agreement with independent evidence.",
    "category": "Research / 001",
    "publishedAt": "2026-09-07T09:00:00Z",
    "cover": {
      "asset": "assets/blog/sensor-fusion.svg",
      "alt": "Three observation paths feed an assessment that retains source relationships and uncertainty.",
      "caption": "Illustrative evidence flow. Agreement between sources does not establish their independence.",
      "animated": true
    },
    "body": [
      {
        "_key": "b0",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b0-end",
            "_type": "span",
            "text": "A supplier says a facility has restarted. A recent image shows a changed storage yard. A vessel has arrived at a nearby port. Three signals, one reassuring story. Has production actually resumed?",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b1",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b1-end",
            "_type": "span",
            "text": "Perhaps. The image could show maintenance. The vessel could be serving another facility. The supplier's statement could be the source of the news report you counted as independent confirmation. A system that combines these observations too eagerly can become more confident while learning very little.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b2",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b2-end",
            "_type": "span",
            "text": "This is the question behind our early sensor-fusion explorations at Goodboy: how can a system reduce uncertainty about the physical world while remaining honest about what it cannot observe? We are exploring an architecture and its evaluation, not announcing a deployed facility-monitoring service.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b3",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b3-end",
            "_type": "span",
            "text": "The starting point is a decision that needs evidence. The choice of sensor comes after that.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b4",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b4-end",
            "_type": "span",
            "text": "Define the claim before collecting the feeds",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b5",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b5-end",
            "_type": "span",
            "text": "“Is the supplier operating?” hides several different questions. Has the site opened? Is equipment running? Is it making the part we need? Can it fulfil our order on time? Evidence for one does not automatically answer the others.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b6",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b6-end",
            "_type": "span",
            "text": "For an initial experiment, we would narrow the target: did activity at a particular facility change during a specified interval in a way consistent with a reported restart? That question identifies an entity, a time window, and an observable comparison. It also leaves room for an inconclusive answer.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b7",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b7-end",
            "_type": "span",
            "text": "The system needs to preserve three layers. An observation describes what a source recorded. An interpretation describes what that could mean. An assessment states what the combined evidence supports. If an image classifier produces “yard activity increased,” that is already an interpretation of pixels. Calling the final output “verified production” would skip several steps.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b8",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b8-end",
            "_type": "span",
            "text": "This discipline makes a modest question considerably more useful than an impressive-looking global map.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b9",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b9-end",
            "_type": "span",
            "text": "Different sensors leave different gaps",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b10",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b10-t0",
            "_type": "span",
            "text": "Optical imagery can help compare visible land use, storage areas, or construction. It has limits. Sentinel-2's instrument samples bands at 10, 20, and 60 metres. Those are spatial sampling scales, not a promise that a system can identify individual operations inside a building. ",
            "marks": []
          },
          {
            "_key": "b10-a0",
            "_type": "span",
            "text": "ESA: Sentinel-2 instrument overview",
            "marks": [
              "b10-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b10-link0",
            "_type": "link",
            "href": "https://step.esa.int/main/wp-content/help/versions/11.0.0/snap-toolboxes/eu.esa.opt.opttbx.s2msi.reader/Sentinel2Overview.html"
          }
        ]
      },
      {
        "_key": "b11",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b11-t0",
            "_type": "span",
            "text": "Sentinel-1 supplies radar imagery in daylight or darkness and through cloud. That makes it complementary to optical observation, but radar backscatter still requires interpretation. A radar change is not a direct reading of production output. ",
            "marks": []
          },
          {
            "_key": "b11-a0",
            "_type": "span",
            "text": "ESA: Sentinel-1",
            "marks": [
              "b11-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b11-link0",
            "_type": "link",
            "href": "https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-1"
          }
        ]
      },
      {
        "_key": "b12",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b12-t0",
            "_type": "span",
            "text": "AIS adds another kind of observation: broadcasts associated with vessels. Missing messages are not necessarily proof of intentional silence, and inferred activity is not a direct observation of cargo ownership. Global Fishing Watch explicitly documents completeness, reception, and interpretation limits in its event data. ",
            "marks": []
          },
          {
            "_key": "b12-a0",
            "_type": "span",
            "text": "Global Fishing Watch: data caveats",
            "marks": [
              "b12-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b12-link0",
            "_type": "link",
            "href": "https://api-doc.globalfishingwatch.org/our-apis/documentation/docs/v3/general-api-doc/data-caveats"
          }
        ]
      },
      {
        "_key": "b13",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b13-end",
            "_type": "span",
            "text": "In our proposed facility experiment, a port arrival would therefore be contextual evidence. Connecting it to a supplier would require a defensible relationship, rather than a convenient line drawn on a map. A feed earns its place when it answers part of the question at an appropriate resolution and time scale.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b14",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b14-end",
            "_type": "span",
            "text": "Three sources can contain one piece of evidence",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b15",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b15-end",
            "_type": "span",
            "text": "Suppose a company publishes a restart notice. A trade publication reports that notice. A data vendor extracts the publication into a structured event. Treating all three as independent votes would reward the distribution of the story rather than the strength of the evidence.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b16",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b16-end",
            "_type": "span",
            "text": "A useful system would retain the original source and the derivation chain. It could still keep all three records: one provides the statement, another adds context, and the third offers a searchable representation. They should not silently become three confirmations.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b17",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b17-t0",
            "_type": "span",
            "text": "Dependence also appears in numerical estimates. Two models can share training data or use the same underlying sensor. Research on Bayesian fusion explicitly examines cases where cross-correlation between estimates is unknown. The practical lesson is to make dependence an engineering concern before multiplying confidence scores. ",
            "marks": []
          },
          {
            "_key": "b17-a0",
            "_type": "span",
            "text": "A Bayesian Approach to Data Fusion in Sensor Networks",
            "marks": [
              "b17-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b17-link0",
            "_type": "link",
            "href": "https://arxiv.org/abs/1303.2414"
          }
        ]
      },
      {
        "_key": "b18",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b18-end",
            "_type": "span",
            "text": "For a first system, we would make source families visible and use conservative combination rules. We would rather display two genuinely different observations than claim ten sources agree when nine copied the tenth.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b19",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b19-end",
            "_type": "span",
            "text": "Keep the time attached",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b20",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b20-end",
            "_type": "span",
            "text": "Here is a fictional assessment made at noon on Friday. A supplier notice arrived that morning. The latest usable image was acquired on Tuesday but downloaded on Thursday. A vessel position was observed on Friday morning. These records do not describe one simultaneous scene.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b21",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b21-end",
            "_type": "span",
            "text": "Each needs at least an observation time, an arrival time, an entity reference, and a source. An assessment can then say that it contains fresh shipping context but stale visual evidence. If a newer image is cloud-obscured, that is a gap in observation. It does not establish that the facility became inactive.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b22",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b22-end",
            "_type": "span",
            "text": "The distinction matters when evaluating early warning. A retrospective model that sees a Monday event report while pretending to make a decision on the preceding Friday has been given the answer. We would replay evidence in arrival order and require the system to work with only what was available at each assessment time.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b23",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b23-end",
            "_type": "span",
            "text": "History should improve an assessment without rewriting what was knowable then.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b24",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b24-end",
            "_type": "span",
            "text": "Give AI a defined place in the pipeline",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b25",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b25-end",
            "_type": "span",
            "text": "Before a model sees these records, the system should resolve their entity references, preserve their origins, and exclude information outside the assessment window. This produces an evidence package for a specific question. A folder full of feeds is a less useful interface.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b26",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b26-end",
            "_type": "span",
            "text": "The model can then propose interpretations, identify contradictions, or explain which missing observation would change the assessment. Its output should refer back to the records it used. It should not invent a relationship between a vessel and a facility simply because that would complete the story.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b27",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b27-end",
            "_type": "span",
            "text": "A separate check can compare the assessment with new observations or a resolved outcome. This is the unified system we are interested in: collection, interpretation, and verification connected through explicit records. AI performs a defined piece of the reasoning, while the surrounding pipeline makes that reasoning inspectable.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b28",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b28-end",
            "_type": "span",
            "text": "Confidence needs a test set",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b29",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b29-t0",
            "_type": "span",
            "text": "A percentage is easy to produce. Giving it a stable meaning is harder. If a system labels comparable assessments as 80 percent likely, calibration asks whether approximately that proportion turns out to be correct over enough resolved cases. Guo and colleagues studied this distinction between prediction accuracy and confidence calibration in neural classifiers. Their results motivate measurement; they do not calibrate our proposed system for us. ",
            "marks": []
          },
          {
            "_key": "b29-a0",
            "_type": "span",
            "text": "On Calibration of Modern Neural Networks",
            "marks": [
              "b29-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b29-link0",
            "_type": "link",
            "href": "https://proceedings.mlr.press/v70/guo17a.html"
          }
        ]
      },
      {
        "_key": "b30",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b30-end",
            "_type": "span",
            "text": "Our first evaluation would use a bounded set of facilities and events with independently established outcomes. We would test detection time, false alarms, missed events, and the rate of inconclusive assessments. We would also remove individual feeds to find out whether they add useful information, and test performance when a source is late or absent.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b31",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b31-end",
            "_type": "span",
            "text": "The output should include the claim, supporting and conflicting observations, relevant gaps, and the next check that would reduce uncertainty. Sometimes that next check will be a call to the facility. Sensors are tools; choosing a better tool is allowed.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b32",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b32-end",
            "_type": "span",
            "text": "The capability we want is an assessment that another person can inspect and challenge. A system that can explain why it is uncertain is a better starting point than one that sounds certain on schedule.",
            "marks": []
          }
        ],
        "markDefs": []
      }
    ]
  },
  {
    "slug": "a-factory-simulator-should-explain-a-late-part",
    "title": "A factory simulator should be able to explain a late part",
    "excerpt": "Inside Factory OS: finite buffers, shared workers, and the difference between a busy animation and a useful model.",
    "category": "Factory OS / 002",
    "publishedAt": "2026-09-07T09:00:00Z",
    "cover": {
      "asset": "assets/blog/factory-flow.svg",
      "alt": "Paused inspection fills two buffer slots, leaving a third completed part blocked at processing.",
      "caption": "Illustrative model: two waiting parts fill the buffer; the third remains on the processing machine.",
      "animated": true
    },
    "body": [
      {
        "_key": "b0",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b0-end",
            "_type": "span",
            "text": "A machine stops. Twenty minutes later, a different machine stops too. Nothing has broken on the second machine. It has finished its work and has nowhere to put it.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b1",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b1-end",
            "_type": "span",
            "text": "That distinction is easy to lose in a dashboard. Both machines look inactive. The causes, and the useful responses, are different.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b2",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b2-end",
            "_type": "span",
            "text": "This is the kind of problem behind our Factory OS research. We are building systems that can help people understand complicated operations. To investigate those systems, we need an environment where delays have causes, actions have consequences, and an explanation can be checked against what actually happened.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b3",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b3-end",
            "_type": "span",
            "text": "Our starting point is a local industrial operations simulator. It is an early, synthetic research prototype. Its machines and work items follow executable rules, but its operating rates are assumptions. We have not validated it against a real production cell. That boundary matters more than how convincing the animation looks.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b4",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b4-end",
            "_type": "span",
            "text": "Start with the queue",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b5",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b5-end",
            "_type": "span",
            "text": "Consider an illustrative line with three stations: preparation, processing, and inspection. Preparation finishes one part every two minutes. Processing takes three minutes. Inspection normally takes one minute. A buffer between processing and inspection holds two waiting parts.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b6",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b6-end",
            "_type": "span",
            "text": "Now pause inspection for ten minutes. Suppose the buffer is empty at the start, and processing completes parts at minutes three, six, and nine. The first two parts fill the buffer. At minute nine, the third finished part cannot leave processing. Under a rule where a machine keeps its finished part until downstream space becomes available, processing is now blocked.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b7",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b7-end",
            "_type": "span",
            "text": "Preparation may continue briefly. Eventually its downstream queue fills as well. The disruption travels upstream through finite storage, even though those upstream machines remain mechanically healthy.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b8",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b8-end",
            "_type": "span",
            "text": "The numbers here are deliberately simple and illustrative; they are not results from an observed factory. They make the causal chain inspectable. If a simulator lets finished parts disappear into unlimited storage, this blocking never occurs. It can report an improvement that the physical operation has no room to accommodate.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b9",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b9-end",
            "_type": "span",
            "text": "This also changes the intervention. Increasing preparation speed cannot reopen inspection. Adding buffer capacity might absorb a short interruption, while increasing work in progress. Assigning another qualified inspector could help only if one is available and inspection is the actual constraint. Each suggestion needs an explicit model of what it consumes and what it changes.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b10",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b10-end",
            "_type": "span",
            "text": "A worker is a resource, not a label",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b11",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b11-end",
            "_type": "span",
            "text": "Our prototype separates setup, loading, processing, and unloading. It distinguishes work that occupies an operator throughout from automatic processing that can release the operator after loading.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b12",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b12-end",
            "_type": "span",
            "text": "That difference can change the answer to a staffing question. Two automatic machines might share a loader while they run. Two manual operations may compete continuously for the same person. Writing “one operator per machine” into both models would hide that distinction.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b13",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b13-t0",
            "_type": "span",
            "text": "Maintenance creates another shared constraint. A repair duration alone does not tell us how long a machine will be unavailable. It may first wait for a technician who is already repairing something else. SimPy's machine-shop example demonstrates this directly through interrupted machine processes competing for repair capacity. We use the same general discrete-event approach: scheduled changes and resource requests drive the operation. ",
            "marks": []
          },
          {
            "_key": "b13-a0",
            "_type": "span",
            "text": "SimPy machine-shop example",
            "marks": [
              "b13-link0"
            ]
          },
          {
            "_key": "b13-end",
            "_type": "span",
            "text": ".",
            "marks": []
          }
        ],
        "markDefs": [
          {
            "_key": "b13-link0",
            "_type": "link",
            "href": "https://simpy.readthedocs.io/en/latest/examples/machine_shop.html"
          }
        ]
      },
      {
        "_key": "b14",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b14-end",
            "_type": "span",
            "text": "These mechanisms give a systems experiment something meaningful to reason about: capacity, eligibility, interruptions, repairs, inspection, and rework. Their presence does not make fictional timings representative of a particular workshop.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b15",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b15-end",
            "_type": "span",
            "text": "Keep the clock honest",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b16",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b16-end",
            "_type": "span",
            "text": "The simulation clock and the screen refresh rate have different jobs. The engine determines when work changes state. The interface makes those changes legible.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b17",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b17-end",
            "_type": "span",
            "text": "Speeding up an animation should not create production. Opening another browser window should not change a random draw. A result should depend on the model, starting conditions, random streams, and timed interventions.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b18",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b18-t0",
            "_type": "span",
            "text": "Ordering also matters. A repair completion and a shift closure can share a timestamp while still requiring an explicit processing order. SimPy processes events sequentially and uses a strictly increasing event identifier to break scheduling ties. That provides deterministic ordering; we still have to make sure our operating rules mean what we intend. ",
            "marks": []
          },
          {
            "_key": "b18-a0",
            "_type": "span",
            "text": "SimPy time and scheduling",
            "marks": [
              "b18-link0"
            ]
          },
          {
            "_key": "b18-end",
            "_type": "span",
            "text": ".",
            "marks": []
          }
        ],
        "markDefs": [
          {
            "_key": "b18-link0",
            "_type": "link",
            "href": "https://simpy.readthedocs.io/en/latest/topical_guides/time_and_scheduling.html"
          }
        ]
      },
      {
        "_key": "b19",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b19-end",
            "_type": "span",
            "text": "Our event records and saved observations let us inspect a run. They do not yet let us restore an arbitrary historical moment and continue down a different branch. A saved view omits the pending processes, resource waiters, and random-generator state needed for that promise. Calling it replay is convenient. Calling it a resumable experiment would currently be wrong.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b20",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b20-end",
            "_type": "span",
            "text": "What happened, and what was knowable",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b21",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b21-end",
            "_type": "span",
            "text": "A future evaluation needs a second clock: when evidence becomes available.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b22",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b22-end",
            "_type": "span",
            "text": "Imagine a simulated stop at 10:05. A status update arrives at 10:08. An operator note arrives at 10:12. An agent assessed at 10:07 must not receive either future message. Otherwise it is being tested with information nobody had at the time.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b23",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b23-t0",
            "_type": "span",
            "text": "OPC UA provides a useful reference by distinguishing source and server timestamps and attaching status information to values. Those fields help preserve context that a bare number cannot carry. For our research, this is a useful design reference for a future observation pipeline, rather than a claim that industrial data is already connected. ",
            "marks": []
          },
          {
            "_key": "b23-a0",
            "_type": "span",
            "text": "OPC UA DataValue",
            "marks": [
              "b23-link0"
            ]
          },
          {
            "_key": "b23-end",
            "_type": "span",
            "text": ".",
            "marks": []
          }
        ],
        "markDefs": [
          {
            "_key": "b23-link0",
            "_type": "link",
            "href": "https://reference.opcfoundation.org/specs/OPC-10000-4/7.11"
          }
        ]
      },
      {
        "_key": "b24",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b24-end",
            "_type": "span",
            "text": "That is also where we would give AI access: a time-bounded view of observations and relevant operating rules, rather than unrestricted access to the simulator’s future. The model could propose a cause or an intervention; a separate simulation run could test its consequences.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b25",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b25-end",
            "_type": "span",
            "text": "Once that observation boundary exists, we can ask better questions: how early was a delivery risk detectable, which evidence supported it, and did the proposed action improve the outcome? Fluent explanations alone would be a very forgiving scoring system.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b26",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b26-end",
            "_type": "span",
            "text": "Earn the model's credibility",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b27",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b27-t0",
            "_type": "span",
            "text": "We can verify that queues respect capacity and parts follow their routes. Establishing that those rules represent an actual operation requires different evidence. Simulation validation is purpose-specific: accuracy sufficient for one question or operating condition does not establish accuracy everywhere. ",
            "marks": []
          },
          {
            "_key": "b27-a0",
            "_type": "span",
            "text": "Robert G. Sargent, Verification and Validation of Simulation Models",
            "marks": [
              "b27-link0"
            ]
          },
          {
            "_key": "b27-end",
            "_type": "span",
            "text": ".",
            "marks": []
          }
        ],
        "markDefs": [
          {
            "_key": "b27-link0",
            "_type": "link",
            "href": "https://www.informs-sim.org/wsc11papers/016.pdf"
          }
        ]
      },
      {
        "_key": "b28",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b28-end",
            "_type": "span",
            "text": "Our next useful reference is one carefully observed cell. We would collect phase durations, staffing rules, buffer sizes, interruption outcomes, and starting work in progress. Then compare the model with a separate observed period, checking queue histories and waiting causes alongside completed output. Every input should retain its origin: measured, reported, or assumed.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b29",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b29-end",
            "_type": "span",
            "text": "A useful simulator makes an assumption easier to challenge. When a part arrives late, we want to follow the chain back through the queue, the resource conflict, and the evidence. That is a better foundation for intelligent industrial software than a factory that merely looks busy.",
            "marks": []
          }
        ],
        "markDefs": []
      }
    ]
  },
  {
    "slug": "memory-that-can-show-its-working",
    "title": "A memory graph should be able to show its working",
    "excerpt": "Notes from Julia on evidence, corrections, access boundaries, and context worth retrieving.",
    "category": "Julia / 003",
    "publishedAt": "2026-09-07T09:00:00Z",
    "cover": {
      "asset": "assets/blog/evidence-memory.svg",
      "alt": "A new instruction supersedes an old assertion while source evidence remains behind a scope boundary.",
      "caption": "A correction changes what is current without erasing the evidence for earlier decisions.",
      "animated": true
    },
    "body": [
      {
        "_key": "b0",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b0-end",
            "_type": "span",
            "text": "A useful assistant should understand a request like “continue the analysis we discussed last week.” That sentence leaves out almost everything a computer needs: which conversation, which dataset, which version of the analysis, and what “continue” permits it to do. The missing information lives across messages, files, decisions, and unfinished work.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b1",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b1-end",
            "_type": "span",
            "text": "Our Julia experiments began with that problem. The ambition is a messaging interface to work that needs a computer: finding local material, running an analysis, continuing a development task, and returning a result. The interesting engineering question is how the system reconstructs enough context to act without turning every answer into an archaeological expedition.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b2",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b2-end",
            "_type": "span",
            "text": "Julia is the context layer in this picture: a memory that connects conversations, artifacts, and decisions across tools. Its value comes from recovering a useful relationship: this file belongs to that analysis, which followed this instruction. The graph matters because the connections mean something, not because it gives us a pleasing way to draw the data.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b3",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b3-end",
            "_type": "span",
            "text": "Start with a claim and its receipt",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b4",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b4-end",
            "_type": "span",
            "text": "Consider a fictional sequence. On Monday, someone writes, “Use the February export for the baseline.” On Thursday, they correct it: “The February export is incomplete. Use March.” An assistant that compresses both messages into “the baseline uses an export” has preserved the topic and lost the decision.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b5",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b5-end",
            "_type": "span",
            "text": "Julia separates original evidence from assertions derived from it. Evidence records retain where a statement came from, when it was made, and who made it. An assertion describes a subject, a relationship or value, supporting evidence, and a status. Confirmed, inferred, disputed, and superseded are different states.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b6",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b6-end",
            "_type": "span",
            "text": "That last detail matters. A recorded user statement can be confirmed as a statement without being independently verified as a fact about the world. Confidence in attribution is not the same as confidence in reality. If a model infers that a particular dataset is suitable, the inference needs to remain distinguishable from a user's instruction to use it.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b7",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b7-t0",
            "_type": "span",
            "text": "This draws on a well-established idea. W3C's PROV model describes entities, activities, and agents involved in producing information, including derivation and revision. It provides a vocabulary for tracing a result back through its origins. Julia is not presented as a PROV implementation; the useful design lesson is to preserve those origins instead of flattening them into a persuasive sentence. ",
            "marks": []
          },
          {
            "_key": "b7-a0",
            "_type": "span",
            "text": "W3C PROV Model Primer",
            "marks": [
              "b7-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b7-link0",
            "_type": "link",
            "href": "https://www.w3.org/TR/prov-primer/"
          }
        ]
      },
      {
        "_key": "b8",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b8-end",
            "_type": "span",
            "text": "Corrections need a history",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b9",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b9-end",
            "_type": "span",
            "text": "In the current prototype, correcting an assertion creates a replacement linked to the earlier record. The older assertion becomes superseded, its period of validity ends, and ordinary recall stops treating it as current. The new claim has its own evidence.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b10",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b10-end",
            "_type": "span",
            "text": "For the export example, ordinary recall should surface the March instruction. Inspection should still explain why an older analysis used February. Both are legitimate questions. Destructively replacing the text would make the second harder to answer; retaining both as equally current would make the first unreliable.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b11",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b11-t0",
            "_type": "span",
            "text": "Temporal memory research treats changing relationships as a first-class concern. The Zep paper describes an agent-memory architecture built around a temporal knowledge graph. We take that as a useful reference for representing change, not as evidence that our own retrieval works equally well. Architecture diagrams do not transfer benchmark results between implementations. ",
            "marks": []
          },
          {
            "_key": "b11-a0",
            "_type": "span",
            "text": "Zep: A Temporal Knowledge Graph Architecture for Agent Memory",
            "marks": [
              "b11-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b11-link0",
            "_type": "link",
            "href": "https://arxiv.org/abs/2501.13956"
          }
        ]
      },
      {
        "_key": "b12",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b12-end",
            "_type": "span",
            "text": "There is also a boundary memory cannot cross by itself. “The file was available yesterday” does not establish that it exists now. Julia's context package can flag a need for fresh observation. Before executing the analysis, the worker should inspect the file and its current state. Stored knowledge helps locate the evidence; a tool observation checks the present.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b13",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b13-end",
            "_type": "span",
            "text": "Permission comes before relevance",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b14",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b14-end",
            "_type": "span",
            "text": "A memory system used by more than one person cannot treat access control as a final filter on generated prose. By then, unauthorized information may already have influenced retrieval, ranking, or an answer.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b15",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b15-end",
            "_type": "span",
            "text": "Julia's memory boundary first resolves the private and group scopes visible to the requesting person. Retrieval operates within that set. Graph traversal uses scoped assertions, and sharing creates a publication of a selected claim. It does not simply grant access to the original private message, its aliases, or its metadata.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b16",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b16-end",
            "_type": "span",
            "text": "That choice has a cost: shared information needs its own lifecycle. A correction or revocation must affect published copies as well as the private source. The prototype handles those links explicitly. The alternative is deceptively easy: a private record changes while an old shared copy remains authoritative forever.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b17",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b17-end",
            "_type": "span",
            "text": "These controls concern application access. They do not imply local model inference, encrypted computation, or protection against every person with direct access to the host. Those are separate boundaries with separate implementations.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b18",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b18-end",
            "_type": "span",
            "text": "Retrieval is a budgeted investigation",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b19",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b19-end",
            "_type": "span",
            "text": "Names, filenames, and exact identifiers deserve exact matching. Paraphrased concepts benefit from semantic matching. Typed relationships help recover the connection between a project, a task, and its output. No single method covers all three well.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b20",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b20-end",
            "_type": "span",
            "text": "The useful combination is exact lookup, semantic retrieval, and a short traversal over known relationships. An AI asked to continue an analysis should receive the relevant decision and artifact, with enough source information to inspect them. It should not need the entire history of the company in its prompt.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b21",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b21-end",
            "_type": "span",
            "text": "This is one of the places AI can enter a larger pipeline. Retrieval assembles candidate evidence within the permitted scope. The model interprets that evidence for the current task. A fresh observation checks anything that may have changed. Execution follows only when the request and permissions support it.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b22",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b22-t0",
            "_type": "span",
            "text": "More context is not automatically more usable context. The “Lost in the Middle” experiments found that the tested models' performance could depend substantially on where relevant material appeared in a long input. Those results concern particular models and tasks; they are a reason to evaluate context selection, not a universal verdict on current models. ",
            "marks": []
          },
          {
            "_key": "b22-a0",
            "_type": "span",
            "text": "Lost in the Middle",
            "marks": [
              "b22-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b22-link0",
            "_type": "link",
            "href": "https://arxiv.org/abs/2307.03172"
          }
        ]
      },
      {
        "_key": "b23",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b23-end",
            "_type": "span",
            "text": "Our practical direction is a compact first pass with evidence available for further inspection. A worker should be able to ask for the underlying message when a decision depends on it. That makes omission recoverable without loading every source into every turn.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b24",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b24-end",
            "_type": "span",
            "text": "The test is whether work resumes correctly",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b25",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b25-end",
            "_type": "span",
            "text": "A larger graph would be an easy demonstration. A better test is a small set of difficult questions with known answers: distinguish two similarly named people; follow a corrected instruction; recover a rarely used file; reject a plausible but unsupported relationship; refuse recall outside the caller's scope.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b26",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b26-end",
            "_type": "span",
            "text": "We would measure answer correctness, source correctness, privacy failures, retrieval latency, and context size separately. An answer with the right conclusion but the wrong receipt is still a failure worth investigating.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b27",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b27-end",
            "_type": "span",
            "text": "Julia is our working exploration of these boundaries. The ambition is continuity across tools and conversations, while retaining a clear distinction between evidence, inference, and permission. The next useful milestone is narrower: recover the right conversation and artifact, explain the relevant decision, inspect the current state, and continue the correct task. Every connection should earn its place by helping that happen.",
            "marks": []
          }
        ],
        "markDefs": []
      }
    ]
  },
  {
    "slug": "a-transcript-is-not-a-handoff",
    "title": "A transcript is not a handoff",
    "excerpt": "What Talkify needs to preserve between a passing thought, a reviewed brief, and a piece of work.",
    "category": "Talkify / 004",
    "publishedAt": "2026-09-07T09:00:00Z",
    "cover": {
      "asset": "assets/blog/voice-handoff.svg",
      "alt": "Original speech is preserved as a source before a structured brief passes an explicit review gate to a job.",
      "caption": "Source capture, interpretation, review, and execution are separate stages with separate responsibilities.",
      "animated": true
    },
    "body": [
      {
        "_key": "b0",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b0-end",
            "_type": "span",
            "text": "An idea arrives while you are doing something else. You speak it, get a reasonably accurate transcript, and carry on. Two days later, the words are still there. The project, the constraint, and the reason it mattered have disappeared.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b1",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b1-end",
            "_type": "span",
            "text": "Speech recognition handled one part of that transaction. The system still has to preserve what the words were for.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b2",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b2-end",
            "_type": "span",
            "text": "Our work on a development fork of Talkify starts with a different requirement: preserve enough of the moment that work can continue later. The upstream application provides a native macOS dictation foundation. We are extending it into a local voice workspace, with original captures, project vocabulary, organized ideas, and deliberate task handoffs. This is development work, not a claim of a finished autonomous assistant.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b3",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b3-end",
            "_type": "span",
            "text": "Talkify is the point where spoken intent enters that wider system. The interesting engineering sits between the microphone and the task queue.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b4",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b4-end",
            "_type": "span",
            "text": "Save before understanding",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b5",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b5-end",
            "_type": "span",
            "text": "Consider this illustrative capture:",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b6",
        "_type": "block",
        "style": "blockquote",
        "children": [
          {
            "_key": "b6-end",
            "_type": "span",
            "text": "“For the factory simulator, show why a machine is waiting. Keep the current graph. Maybe start with the repair queue. Just save this for later.”",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b7",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b7-end",
            "_type": "span",
            "text": "A useful system can suggest a title, a project, a constraint, and a possible first step. It must also preserve “maybe” and “just save.” Converting a tentative thought into a firm implementation plan changes its meaning. Starting work changes its consequences.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b8",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b8-end",
            "_type": "span",
            "text": "Our capture design saves the original transcript before organization begins. The structured idea is a second record linked back to those words. If the local model is unavailable or organization fails, the capture still exists. The user can revise the interpretation without losing the source.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b9",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b9-end",
            "_type": "span",
            "text": "A model can propose a project, extract constraints, and turn a rambling note into a useful brief. Giving it that specific job is different from letting it decide the next action. The source capture, its interpretation, and permission to execute belong at different points in the pipeline.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b10",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b10-end",
            "_type": "span",
            "text": "That distinction sets the architecture: storage owns durability; the model proposes organization. The model does not decide whether the thought deserves to survive.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b11",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b11-end",
            "_type": "span",
            "text": "Keep the uncertain parts visible",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b12",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b12-t0",
            "_type": "span",
            "text": "Even the transcript is not a single instantaneous fact. Streaming speech systems revise provisional results as more audio arrives. Apple’s SpeechAnalyzer explicitly distinguishes a volatile range, which may change, from results that are no longer subject to replacement. ",
            "marks": []
          },
          {
            "_key": "b12-a0",
            "_type": "span",
            "text": "Apple: volatile results",
            "marks": [
              "b12-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b12-link0",
            "_type": "link",
            "href": "https://developer.apple.com/documentation/speech/speechanalyzer/volatilerange"
          }
        ]
      },
      {
        "_key": "b13",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b13-end",
            "_type": "span",
            "text": "A voice interface needs that distinction. Showing provisional text quickly makes speaking feel responsive. Treating every provisional phrase as a command would make it erratic. Display, final capture, and execution need separate transitions.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b14",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b14-end",
            "_type": "span",
            "text": "Vocabulary adds another layer. Project names and identifiers often look wrong to a general recognizer. A correction should be able to use the chosen project without changing ordinary language everywhere. The broader principle is context with a boundary: use enough information to resolve the ambiguity, and preserve the original when the interpretation changes.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b15",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b15-end",
            "_type": "span",
            "text": "Context needs a job description",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b16",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b16-end",
            "_type": "span",
            "text": "The longer-term inspiration is the fusion of several observations into a usable account of the current situation. In a software workspace, those observations might be speech, selected text, a project, previous decisions, and execution state. The important idea is that different inputs supply different parts of the answer.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b17",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b17-end",
            "_type": "span",
            "text": "Each input should answer a specific question. Speech expresses intent. A selected object can identify what “this” refers to. Current state says what is happening. Earlier notes explain prior decisions. They are not interchangeable evidence.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b18",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b18-end",
            "_type": "span",
            "text": "Suppose an operator selects a simulated machine and asks, “Why is this waiting again?” The selected machine identifies the subject. Its current state and recent events are the evidence to investigate. Yesterday’s note about staffing is a possible lead. It cannot establish today’s cause by itself.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b19",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b19-end",
            "_type": "span",
            "text": "That Factory OS interaction remains a proposed integration. The direction starts with a narrower set of inputs: application context, a chosen project, and selected text when the user chooses to include it. The useful rule already applies: attach context deliberately, preserve where it came from, and avoid promoting a guess into an observation.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b20",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b20-end",
            "_type": "span",
            "text": "Collecting everything is not the same as understanding the relevant thing.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b21",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b21-end",
            "_type": "span",
            "text": "Execution deserves its own boundary",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b22",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b22-end",
            "_type": "span",
            "text": "“Save this idea,” “prepare a brief,” and “work on this” are different requests. Our design treats them differently. Ordinary captures stay in the local inbox. A prepared brief gives the user a review point. Direct voice queueing requires an explicit setting and a selected project; a model-generated interpretation cannot authorize execution.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b23",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b23-end",
            "_type": "span",
            "text": "The brief needs more than a polished summary. It should carry the objective, known constraints, relevant context, and a definition of done. “Keep the current graph” belongs beside the proposed change, where the next system can see it. Otherwise a helpful rewrite becomes a redesign nobody requested.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b24",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b24-end",
            "_type": "span",
            "text": "The local boundary is similarly concrete. Capturing and organizing a thought on-device does not make every later operation local. A handoff to an external coding provider sends the supplied brief outside that local workflow. The interface should distinguish saved, prepared, and sent states without making the user reconstruct the architecture.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b25",
        "_type": "block",
        "style": "h2",
        "children": [
          {
            "_key": "b25-end",
            "_type": "span",
            "text": "A timeout is not a verdict",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b26",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b26-end",
            "_type": "span",
            "text": "Once a brief becomes a job, the problem is partly distributed systems engineering. Imagine the receiving process starts work, but the sender loses the acknowledgment. Blindly retrying could create a second job. Declaring failure could hide work already underway.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b27",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b27-t0",
            "_type": "span",
            "text": "Amazon’s guidance on idempotent APIs describes this ambiguity and the value of caller-provided request identifiers. Repeated intent needs an identity that survives a retry; matching two similar payloads is not always enough. ",
            "marks": []
          },
          {
            "_key": "b27-a0",
            "_type": "span",
            "text": "Amazon Builders’ Library: safe retries",
            "marks": [
              "b27-link0"
            ]
          }
        ],
        "markDefs": [
          {
            "_key": "b27-link0",
            "_type": "link",
            "href": "https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/"
          }
        ]
      },
      {
        "_key": "b28",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b28-end",
            "_type": "span",
            "text": "For our voice queue, the design consequence is persistent job state and reconciliation after interruption. Keep a reference to the work that was submitted. If submission is uncertain, pause and inspect that recorded work before replaying anything. A confident spinner is not a recovery strategy.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b29",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b29-end",
            "_type": "span",
            "text": "The tests that matter follow these boundaries: does capture survive without a model, does a project correction stay in scope, does an ambiguous command remain a draft, and does a lost acknowledgment produce duplicate work? End-to-end latency matters too, but speed cannot compensate for losing the thought or executing it twice.",
            "marks": []
          }
        ],
        "markDefs": []
      },
      {
        "_key": "b30",
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_key": "b30-end",
            "_type": "span",
            "text": "A good voice workspace lets a person return later and understand what was said, what was inferred, what was authorized, and what actually happened. That is the direction we are exploring: a voice interface connected to a useful system of work, with a clear account of what crossed each boundary.",
            "marks": []
          }
        ],
        "markDefs": []
      }
    ]
  }
];
