#!/usr/bin/env python3
"""Build the local blog data and existing three homepage cards from Markdown.
Run: python3 scripts/build-blog.py
No dependencies, network requests, or publishing steps.
"""
from pathlib import Path
import html
import hashlib
import json
import re
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / 'content/blog'


def inline(text, key):
    children, definitions, position = [], [], 0
    for i, match in enumerate(re.finditer(r'\[([^\]]+)\]\((https?://[^\s)]+)\)', text)):
        if match.start() > position:
            children.append({'_key': f'{key}-t{i}', '_type': 'span', 'text': text[position:match.start()], 'marks': []})
        mark = f'{key}-link{i}'
        definitions.append({'_key': mark, '_type': 'link', 'href': match[2]})
        children.append({'_key': f'{key}-a{i}', '_type': 'span', 'text': match[1], 'marks': [mark]})
        position = match.end()
    if position < len(text):
        children.append({'_key': f'{key}-end', '_type': 'span', 'text': text[position:], 'marks': []})
    return children, definitions


def blocks(markdown):
    result = []
    for paragraph in re.split(r'\n\s*\n', markdown.strip()):
        if paragraph.startswith('# '):
            continue
        style = 'normal'
        if paragraph.startswith('## '):
            style, paragraph = 'h2', paragraph[3:]
        elif paragraph.startswith('### '):
            style, paragraph = 'h3', paragraph[4:]
        elif paragraph.startswith('> '):
            style, paragraph = 'blockquote', paragraph[2:]
        key = f'b{len(result)}'
        children, definitions = inline(' '.join(paragraph.splitlines()), key)
        result.append({'_key': key, '_type': 'block', 'style': style, 'children': children, 'markDefs': definitions})
    return result


posts = json.loads((POSTS / 'posts.json').read_text())
for post in posts:
    source = (POSTS / f"{post['slug']}.md").read_text()
    assert source.startswith(f"# {post['title']}\n"), 'Title mismatch'
    assert 'EVIDENCE NOTES' not in source, 'Internal notes must stay out of public content'
    assert (ROOT / post['cover']['asset']).is_file(), 'Missing illustration'
    post['body'] = blocks(source)
(ROOT / 'js/posts.js').write_text('// Generated by scripts/build-blog.py from content/blog/.\nwindow.GOODBOY_POSTS = '+json.dumps(posts,ensure_ascii=False,indent=2)+';\n')

# Keep local previews and future static hosting consistent after content changes.
for template in ['blog.html', 'post.html']:
    page = ROOT / template
    text = page.read_text()
    for resource in ['js/posts.js', 'js/blog.js', 'css/blog.css']:
        version = hashlib.sha256((ROOT / resource).read_bytes()).hexdigest()[:12]
        text = re.sub(re.escape(resource) + r'(?:\?v=[a-z0-9-]+)?', f'{resource}?v={version}', text)
    page.write_text(text)

cards = []
for post in posts[:3]:
    esc = lambda value: html.escape(value, quote=True)
    date = datetime.fromisoformat(post['publishedAt'].replace('Z', '+00:00')).strftime('%B %d, %Y')
    cards.append(f'''            <article class="note-card reveal-block">
              <a href="post.html?slug={esc(post['slug'])}">
                <div class="note-card__visual" aria-hidden="true"><img src="{esc(post['cover']['asset'])}" alt="" width="1200" height="800" loading="lazy" decoding="async" /></div>
                <p class="note-card__meta">{esc(date)}</p>
                <h3>{esc(post['title'])}</h3>
                <p>{esc(post['excerpt'])}</p>
              </a>
            </article>''')
index = ROOT / 'index.html'
text = index.read_text()
text, count = re.subn(r'(<div class="notes-grid" id="home-notes">)\n[\s\S]*?(\n          </div>\n        </div>\n      </section>)', lambda m: m[1]+'\n'+'\n'.join(cards)+m[2], text, count=1)
assert count == 1, 'Homepage card container not found'
index.write_text(text)
print(f'Built {len(posts)} articles and {len(cards)} homepage cards.')
